---
- name: Example Ansible Playbook
  hosts: all
  become: true
  vars:
    ansible_user: sa_106301816075024666979
   

  pre_tasks:
    - name: Update apt cache
      apt:
        update_cache: yes
        cache_valid_time: 3600

  roles:
    - geerlingguy.apache
